# Generated by `mise run formula` in evoke-build/evoke for each release; edit it there.
class Evoke < Formula
  desc "Turns a sentence into a call of a small program, chosen by a classifier"
  homepage "https://evoke.build"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/evoke-build/evoke/releases/download/v0.18.0/evoke-aarch64-apple-darwin.tar.gz"
      sha256 "c8fe9d9233ce176496e4bebf93ae7c618b3f44a25a1bc9114272d2e02b7d63e7"
    end
    on_intel do
      url "https://github.com/evoke-build/evoke/releases/download/v0.18.0/evoke-x86_64-apple-darwin.tar.gz"
      sha256 "ace7dc1f887fb62113787fc5979ef96aee893adf0c1c1850ca3d1ea7df40f709"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/evoke-build/evoke/releases/download/v0.18.0/evoke-aarch64-unknown-linux-musl.tar.gz"
      sha256 "9e31ba0e2b3351e23223a65723227342d3181e01f4dd216c35170596f706dc93"
    end
    on_intel do
      url "https://github.com/evoke-build/evoke/releases/download/v0.18.0/evoke-x86_64-unknown-linux-musl.tar.gz"
      sha256 "27b129fc5fb839a14ba214b15c75b0dbe7e6b09d3fcd0b5d3a5caa593e58a607"
    end
  end

  def install
    bin.install "evoke"
  end

  test do
    assert_equal "evoke #{version}", shell_output("#{bin}/evoke --version").strip
  end
end
