# Generated by `mise run formula` in evoke-build/evoke for each release; edit it there.
class Evoke < Formula
  desc "Turns a sentence into a call of a small program, chosen by a classifier"
  homepage "https://evoke.build"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/evoke-build/evoke/releases/download/v0.4.0/evoke-aarch64-apple-darwin.tar.gz"
      sha256 "f303f5c04c29affb747ef58d5480fc53bc06d916095dc3b8a11b2705558e17fb"
    end
    on_intel do
      url "https://github.com/evoke-build/evoke/releases/download/v0.4.0/evoke-x86_64-apple-darwin.tar.gz"
      sha256 "348ccf92604fb15ddac95d51c455a5b2107ad88f92433283070c17ac70994085"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/evoke-build/evoke/releases/download/v0.4.0/evoke-aarch64-unknown-linux-musl.tar.gz"
      sha256 "1e9e9d565cc99e658e8f588acdb0d1cfeded0dc31de5935895ca50e904c013aa"
    end
    on_intel do
      url "https://github.com/evoke-build/evoke/releases/download/v0.4.0/evoke-x86_64-unknown-linux-musl.tar.gz"
      sha256 "58d0f074b0b600ca68c13ef2bf85e002446996d7bb08c7ec868a520325a29a61"
    end
  end

  def install
    bin.install "evoke"
  end

  test do
    assert_equal "evoke #{version}", shell_output("#{bin}/evoke --version").strip
  end
end
